name: 'Pull Request'
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16, 18, 20]
        typescript: [
            # '~5.0.4', `switch (true) {` (used in expressions) is not a typeguard until 5.3. TODO: Remove it and reintroduce versions
            # '~5.1.6',
            # '~5.2.2',
            '~5.3.3',
            '~5.4.2',
            'latest'
          ]
    name: Node ${{ matrix.node }} / TS ${{ matrix.typescript }}
    steps:
      - name: â™»ï¸ Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: ğŸ—ï¸ Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: ğŸšš Install dependencies
        run: npm ci --legacy-peer-deps

      - name: ğŸ“Œ Install TS at correct version
        run: npm i typescript@${{ matrix.typescript }}

      - name: ğŸ¯ Run tests
        run: npm test
